cc_binary(
  name = "hightop",
  srcs = ["main.cpp"],
  visibility = ["//visibility:public"],
  deps = [
    "//libhightop:hightop",
    "@ftxui",
    "@grid-container-ftxui",
    "//hightop/ui/ftxui-interactive-table"
  ],
)