cc_library(
  name = "ftxui-interactive-table",
  srcs = glob(["*.cpp"]),
  hdrs = glob(["*.h"]),
  visibility = ["//visibility:public"],
  include_prefix = "ui/ftxui-interactive-table",
  deps = ["@ftxui"]
)
