cc_binary(
  name = "grid-container",
  srcs = ["grid-container.cpp"],
  visibility = ["//visibility:public"],
  deps = [
    "//libhightop:hightop",
    "@ftxui",
    "@grid-container-ftxui"
  ],
)

cc_binary(
  name = "grid-example",
  srcs = ["grid-example.cpp"],
  visibility = ["//visibility:public"],
  deps = [
    "//libhightop:hightop",
    "@ftxui",
    "@grid-container-ftxui"
  ],
)

cc_binary(
  name = "data",
  srcs = ["data.cpp"],
  visibility = ["//visibility:public"],
  deps = [
    "@ftxui",
  ],
)

cc_binary(
  name = "demo",
  srcs = ["demo.cpp"],
  visibility = ["//visibility:public"],
  deps = [
    "//libhightop:hightop",
    "@ftxui",
    "@grid-container-ftxui"
  ],
)

